name: sparc
favicon: null
layout_spectrum: 0.664243669481948
typography_spectrum: 0.94677
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ead7e6'
    - '#bcafad'
    - '#98887c'
    - '#6b615b'
    - '#371918'
  brandStrength: 0.8125
  lightness: 0.15673926379531622
  saturation: 0.375
  rhythmicContrast: 0.5986756847705692
purpose: []
